import React from 'react'
import Link from 'next/link'
import { headers as getHeaders } from 'next/headers'
import { getPayloadHMR } from '@payloadcms/next/utilities'
import configPromise from '@payload-config'
import './index.scss'
import './layout.scss'

const FONT_MAP: Record<string, string> = {
  segoe: "'Segoe UI', system-ui, -apple-system, sans-serif",
  inter: "'Inter', system-ui, sans-serif",
  roboto: "'Roboto', system-ui, sans-serif",
  merriweather: "'Merriweather', Georgia, serif",
}

const baseClass = 'multi-tenant'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const headersList = getHeaders()
  const tenantDomain = headersList.get('x-tenant-domain')

  // Không có domain (localhost dev, admin, api...) → render đơn giản
  if (!tenantDomain) {
    return (
      <html lang="en" className={baseClass}>
        <body>{children}</body>
      </html>
    )
  }

  const payload = await getPayloadHMR({ config: configPromise })

  const [tenantsQuery, settingsQuery] = await Promise.all([
    payload.find({
      collection: 'tenants',
      overrideAccess: true,
      where: { domain: { equals: tenantDomain } },
      limit: 1,
    }),
    payload.find({
      collection: 'site-settings',
      overrideAccess: true,
      where: { 'tenant.domain': { equals: tenantDomain } },
      limit: 1,
    }),
  ])

  const tenant = tenantsQuery.docs?.[0]
  const tenantName = tenant?.name ?? tenantDomain
  const settings = settingsQuery.docs?.[0] as any

  const headerEnabled = settings?.header?.enabled ?? true
  const footerEnabled = settings?.footer?.enabled ?? true
  const topBarEnabled = settings?.header?.topBar?.enabled ?? false
  const logoText = settings?.header?.logoText || tenantName
  const navLinks: { label: string; url: string }[] = settings?.header?.navLinks ?? []
  const footerColumns: { title: string; content: string }[] = settings?.footer?.columns ?? []
  const copyrightText =
    settings?.footer?.copyrightText ??
    `© ${new Date().getFullYear()} ${tenantName}. All rights reserved.`

  const t = settings?.theme ?? {}
  const primaryColor = t.primaryColor ?? '#e84118'
  const darkColor = t.darkColor ?? '#1a1a2e'
  const heroBgFrom = t.heroBgFrom ?? primaryColor
  const heroBgTo = t.heroBgTo ?? '#ffb347'
  const cardRadius = t.cardRadius ?? '16px'
  const fontFamily = FONT_MAP[t.fontFamily] ?? FONT_MAP.segoe

  const cssVars = `
    :root {
      --color-primary: ${primaryColor};
      --color-primary-dark: color-mix(in srgb, ${primaryColor} 80%, black);
      --color-dark: ${darkColor};
      --hero-bg: linear-gradient(135deg, ${heroBgFrom} 0%, ${heroBgTo} 100%);
      --card-radius: ${cardRadius};
      --font-family: ${fontFamily};
    }
  `

  return (
    <html lang="en" className={baseClass}>
      <body>
        <div className="site">
          <style dangerouslySetInnerHTML={{ __html: cssVars }} />

          {headerEnabled && topBarEnabled && (
            <div className="site__topbar">
              <span>{settings?.header?.topBar?.leftText}</span>
              <span>{settings?.header?.topBar?.rightText}</span>
            </div>
          )}

          {headerEnabled && (
            <header className="site__header">
              <div className="site__header-inner">
                <Link href="/" className="site__logo">
                  <span className="site__logo-main">{logoText}</span>
                </Link>

                <nav className="site__nav">
                  {navLinks.length > 0 ? (
                    navLinks.map((link, i) => (
                      <Link key={i} href={link.url}>
                        {link.label}
                      </Link>
                    ))
                  ) : (
                    <>
                      <Link href="/">Trang chủ</Link>
                      <Link href="/tickets">Mua vé</Link>
                    </>
                  )}
                  <Link href="/login" className="site__nav-login">
                    Đăng nhập
                  </Link>
                </nav>
              </div>
            </header>
          )}

          <main className="site__main">{children}</main>

          {footerEnabled && (
            <footer className="site__footer">
              <div className="site__footer-inner">
                {footerColumns.length > 0 ? (
                  footerColumns.map((col, i) => (
                    <div key={i} className="site__footer-col">
                      {col.title && <h4>{col.title}</h4>}
                      {col.content && (
                        <div>
                          {col.content.split('\n').map((line, j) => (
                            <p key={j}>{line}</p>
                          ))}
                        </div>
                      )}
                    </div>
                  ))
                ) : (
                  <>
                    <div className="site__footer-col">
                      <strong>{tenantName}</strong>
                      <p>Dịch vụ đặt vé trực tuyến nhanh chóng, tiện lợi.</p>
                    </div>
                    <div className="site__footer-col">
                      <h4>Liên kết</h4>
                      <Link href="/">Trang chủ</Link>
                      <Link href="/tickets">Danh sách vé</Link>
                    </div>
                    <div className="site__footer-col">
                      <h4>Liên hệ</h4>
                      <p>Email: support@{tenantDomain}</p>
                      <p>Hotline: 1900 xxxx</p>
                    </div>
                  </>
                )}
              </div>
              <div className="site__footer-bottom">{copyrightText}</div>
            </footer>
          )}
        </div>
      </body>
    </html>
  )
}
